// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzstoEh_zxCuQYGWat9TdBf2E33ywXlaA',
    appId: '1:530874384504:web:75a0cb84160cd981f46d8d',
    messagingSenderId: '530874384504',
    projectId: 's-g-co-ilvly5',
    authDomain: 'fir-g-co-ilvly5.firebaseapp.com',
    storageBucket: 's-g-co-ilvly5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYQcZDcw0RBW6zAjK8O18LLW6sIc7Ds5o',
    appId: '1:530874384504:android:24f2e38c05cc22f6f46d8d',
    messagingSenderId: '530874384504',
    projectId: 's-g-co-ilvly5',
    storageBucket: 's-g-co-ilvly5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA2F4z0ZRqnu7bwVJLt6NdIggqumwsTGA',
    appId: '1:530874384504:ios:0b07ea7b698f228ef46d8d',
    messagingSenderId: '530874384504',
    projectId: 's-g-co-ilvly5',
    storageBucket: 's-g-co-ilvly5.firebasestorage.app',
    androidClientId: '530874384504-09vhqegebt9u39o8gisvo4l2ekqnvskk.apps.googleusercontent.com',
    iosClientId: '530874384504-g965tvuclsm2ktj8mh9s6gsf9fo8alrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.sgco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA2F4z0ZRqnu7bwVJLt6NdIggqumwsTGA',
    appId: '1:530874384504:ios:0b07ea7b698f228ef46d8d',
    messagingSenderId: '530874384504',
    projectId: 's-g-co-ilvly5',
    storageBucket: 's-g-co-ilvly5.firebasestorage.app',
    androidClientId: '530874384504-09vhqegebt9u39o8gisvo4l2ekqnvskk.apps.googleusercontent.com',
    iosClientId: '530874384504-g965tvuclsm2ktj8mh9s6gsf9fo8alrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.sgco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzstoEh_zxCuQYGWat9TdBf2E33ywXlaA',
    appId: '1:530874384504:web:713438abb751712cf46d8d',
    messagingSenderId: '530874384504',
    projectId: 's-g-co-ilvly5',
    authDomain: 'fir-g-co-ilvly5.firebaseapp.com',
    storageBucket: 's-g-co-ilvly5.firebasestorage.app',
  );
}
